title: The Antiscam Group
description: The website home to an automated solution for commission solicitors.
url: "https://theantiscamgroup.com"
show_downloads: false
github_username: socksthewolf
remote_theme: pages-themes/cayman@master
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag