name: Deploy Bot
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Adding the Private key to a Github Actions Workflow
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        log-public-key: false
    
    - name: Update Python Project
      uses: appleboy/ssh-action@master
      env:
        GITKEYLOC: ${{ secrets.AUTH_KEY_LOC }}
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        envs: GITKEYLOC
        script: |
          cd ~/project/AntiScamBot
          eval "$(ssh-agent -s)"
          ssh-add $GITKEYLOC
          ssh -T git@github.com
          .runtime/kill.sh
          git pull
          echo "Deploy success"
