name: Deploy Bot
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    env:
      AUTHKEYNAME: ${{ vars.AUTH_KEY_NAME }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    
    - name: Update Check
      uses: dorny/paths-filter@v3.0.2
      id: filter
      with:
        list-files: shell
        base: ${{ github.ref }}
        filters: |
          deps_updated:
            - 'requirements.txt'
            - '.runtime/update.sh'
          core_updated:
            - '.runtime/run.sh'
            - '.github/workflows/deploy.yml'
            - '**.py'

    # Adding the Private key to a Github Actions Workflow
    - name: Install SSH Key
      if: steps.filter.outputs.deps_updated == 'true' || steps.filter.outputs.core_updated == 'true'
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        log-public-key: false

    - name: Update Python Project
      if: steps.filter.outputs.deps_updated == 'true' || steps.filter.outputs.core_updated == 'true'
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        envs: AUTHKEYNAME
        script: |
          echo "Moving to project directory"
          cd ~/project/AntiScamBot
          echo "Setting SSH Agent"
          eval "$(ssh-agent -s)"
          echo "Readding SSH Key"
          ssh-add ~/.ssh/$AUTHKEYNAME
          echo "Checking Git Readability"
          ssh -T git@github.com
          echo "Killing bot..."
          .runtime/kill.sh
          rm nohup.out
          echo "Updating directory"
          git pull
          echo "Deploy success"

    - name: Update Python Dependencies
      if: steps.filter.outputs.deps_updated == 'true'
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        script: |
          echo "Updating project dependencies"
          cd ~/project/AntiScamBot
          .runtime/update.sh
          echo "Finished updating python dependencies"
