name: Deploy Bot
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    env:
      AUTHKEYNAME: ${{ vars.AUTH_KEY_NAME }}
      BOTDIRECTORY: ${{ vars.BOT_DIRECTORY }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v4
    
    - name: Update Check
      uses: dorny/paths-filter@v3.0.2
      id: filter
      with:
        filters: |
          deps_updated:
            - 'requirements.txt'
            - 'update.sh'
          bot_updated:
            - 'run.sh'
            - 'deploy.yml'
            - '**.py'

    # Adding the Private key to a Github Actions Workflow
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        log-public-key: false

    - name: Update Python Project
      uses: appleboy/ssh-action@master
      if: steps.filter.outputs.deps_updated == 'true' || steps.filter.outputs.bot_updated == 'true'
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        envs: AUTHKEYNAME,BOTDIRECTORY
        script: |
          echo "Moving to project directory"
          cd $BOTDIRECTORY
          echo "Setting SSH Agent"
          eval "$(ssh-agent -s)"
          echo "Readding SSH Key"
          ssh-add ~/.ssh/$AUTHKEYNAME
          echo "Checking Git Readability"
          ssh -T git@github.com
          echo "Killing bot..."
          .runtime/kill.sh
          rm nohup.out
          echo "Updating directory"
          git pull
          echo "Deploy success"

    - name: Update Python Dependencies
      if: steps.filter.outputs.deps_updated == 'true'
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        envs: BOTDIRECTORY
        script: |
          echo "Updating project dependencies"
          cd $BOTDIRECTORY
          .runtime/update.sh
          echo "Finished updating python dependencies"
