name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Python
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        script: |
          mkdir project
          cd project
          git clone git@github.com:SocksTheWolf/AntiScamBot.git
          echo "Deploy success"
