name: Deploy Bot
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Update Python Project
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        passphrase: ${{secrets.SSH_PASSPHRASE}}
        script: |
          pwd
          cd project/AntiScamBot
          ./runtime/kill.sh
          git pull
          echo "Deploy success"
