name: Deploy Bot
on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Adding the Private key to a Github Actions Workflow
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        log-public-key: false
    
    - name: Update Python Project
      uses: appleboy/ssh-action@master
      env:
        AUTHKEYNAME: ${{ vars.AUTH_KEY_NAME }}
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        envs: AUTHKEYNAME
        script: |
          echo "Moving to project directory"
          cd ~/project/AntiScamBot
          echo "Setting SSH Agent"
          eval "$(ssh-agent -s)"
          echo "Readding SSH Key"
          ssh-add ~/.ssh/$AUTHKEYNAME
          echo "Checking Git Readability"
          ssh -T git@github.com
          echo "Killing bot..."
          .runtime/kill.sh
          rm nohup.out
          echo "Updating directory"
          git pull
          echo "Deploy success"
